# Netlify configuration
[build]
  # Build command that runs both JS build and Eleventy
  command = "npm run build"
  # Directory containing the built site
  publish = "_site"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]
  
# Node.js version (specify a stable version)
[build.environment]
  NODE_VERSION = "22"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Old portfolio link
[[redirects]]
  from = "/portfolio"
  to = "/works"
  status = 301
  force = false

# Redirect all not-found pages to the generated 404.html
[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

