# Netlify configuration for custom 404 page

# Redirect all not-found pages to the generated 404.html
[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
